require 'pry'
require 'nokogiri'
require 'open-uri'
require 'uri'
require 'openssl'
require 'json'

require_relative '../lib/game_info/cli'
require_relative '../lib/game_info/game'
require_relative '../lib/game_info/scraper'
